# Correlation Between Ranking/Tour Level Matches Played and Prize Money Earned

The correlation between player rankings and prize money earned as well as tour level matches played and prize money earned is calculated by ranking band (1-50, 50-100, etc.) for each year for singles and doubles separately. The correlations illustrate how related the two variables are to each other.

In [5]:
import pandas as pd
import datetime
import numpy as np

In [6]:
START_YEAR = 2009
END_YEAR = datetime.datetime.now().year - 1
MAX_SINGLES = 750
MAX_DOUBLES = 250

In [7]:
data = []
for year in range(START_YEAR, END_YEAR + 1):
    singles = pd.read_csv(f"../data/players/clean/singles/{year}.gz")

    band_prize_money = 0
    band_prize_money_array = []
    band_matches_played = 0
    band_matches_played_array = []
    band_ranking_array = []

    for rank in range(1, MAX_SINGLES + 1):
        player = singles.loc[singles["ranking"] == rank]
        if not player.empty:
            band_prize_money += player["prize_money"].iloc[0]
            band_prize_money_array.append(player["prize_money"].iloc[0])
            band_matches_played += player["wins"].iloc[0] + player["losses"].iloc[0]
            band_matches_played_array.append(player["wins"].iloc[0] + player["losses"].iloc[0])
            band_ranking_array.append(rank)

        if rank % 50 == 0:
            matches_correlation = np.corrcoef(band_prize_money_array, band_matches_played_array)[0, 1] ** 2
            ranking_correlation = np.corrcoef(band_prize_money_array, band_ranking_array)[1, 0] ** 2

            data.append({
                "year": year,
                "type": "singles",
                "ranking_band": f"{rank - 49} - {rank}",
                "prize_money": band_prize_money,
                "matches_played": band_matches_played,
                "matches_correlation": matches_correlation,
                "ranking_correlation": ranking_correlation
            })

            band_prize_money = 0
            band_prize_money_array = []
            band_matches_played = 0
            band_matches_played_array = []
            band_ranking_array = []


    doubles = pd.read_csv(f"../data/players/clean/doubles/{year}.gz")

    band_prize_money = 0
    band_prize_money_array = []
    band_matches_played = 0
    band_matches_played_array = []
    band_ranking_array = []

    for rank in range(1, MAX_DOUBLES + 1):
        player = doubles.loc[doubles["ranking"] == rank]
        if not player.empty:
            band_prize_money += player["prize_money"].iloc[0]
            band_prize_money_array.append(player["prize_money"].iloc[0])
            band_matches_played += player["wins"].iloc[0] + player["losses"].iloc[0]
            band_matches_played_array.append(player["wins"].iloc[0] + player["losses"].iloc[0])
            band_ranking_array.append(rank)

        if rank % 50 == 0:
            matches_correlation = np.corrcoef(band_prize_money_array, band_matches_played_array)[0, 1] ** 2
            ranking_correlation = np.corrcoef(band_prize_money_array, band_ranking_array)[1, 0] ** 2

            data.append({
                "year": year,
                "type": "doubles",
                "ranking_band": f"{rank - 49} - {rank}",
                "prize_money": band_prize_money,
                "matches_played": band_matches_played,
                "matches_correlation": matches_correlation,
                "ranking_correlation": ranking_correlation
            })

            band_prize_money = 0
            band_prize_money_array = []
            band_matches_played = 0
            band_matches_played_array = []
            band_ranking_array = []

res = pd.DataFrame(data)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:518: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2845: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2704: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2704: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2853: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [8]:
res

,year,type,ranking_band,prize_money,matches_played,matches_correlation,ranking_correlation
0,2009,singles,1 - 50,98017096.08,2802,0.368244,0.492138
1,2009,singles,51 - 100,19538346.58,1388,0.900065,0.153132
2,2009,singles,101 - 150,11365235.54,712,0.944274,0.229188
3,2009,singles,151 - 200,5370628.86,214,0.877559,0.068774
4,2009,singles,201 - 250,3400908.52,113,0.839129,0.013723
...,...,...,...,...,...,...,...
295,2023,doubles,1 - 50,26275827.00,2491,0.262332,0.838829
296,2023,doubles,51 - 100,5970980.00,1088,0.542548,0.276402
297,2023,doubles,101 - 150,2561730.00,332,0.873555,0.108280
298,2023,doubles,151 - 200,1832061.00,208,0.759774,0.003833
299,2023,doubles,201 - 250,1100115.00,123,0.873728,0.056511